name: build
on: 
  push:
    tags:        
      - '**'
jobs:
#   windows-build:
#     runs-on: windows-2019
#     steps:
#       - run: curl 'https://libsdl.org/release/SDL2-devel-2.0.20-mingw.tar.gz'
#       - run: unzip SDL2-devel-2.0.20-mingw.tar.gz
#       - run: gcc app.c -o app -mwindows -lmingw32 -lSDL2main -lSDL2
  macos-build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: brew update
      - run: brew install sdl2
      - run: clang app.c -o app `sdl2-config --cflags --libs`
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
         files: app
  linux-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install libsdl2-dev
      - run: gcc app.c -o app `sdl2-config --cflags --libs`
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
         files: app
