name: build
on: 
  push:
    tags:        
      - '**'
jobs:
  windows-build:
    runs-on: windows-2019
    steps:
      - run: curl 'https://libsdl.org/release/SDL2-devel-2.0.20-mingw.tar.gz' -o SDL2.tar.gz
      - run: 7z x SDL2.tar.gz -o*
      - run: cp SDL2-2.0.20\x86_64-w64-mingw32\bin\sdl2-config sdl2-config
      - run: sdl2-config --cflags --libs > flags.txt
      - run: set /p FLAGS=<flags.txt
      - run: gcc app.c -o app %FLAGS%
      - run: 7z a -tzip app_windows.zip app
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
         files: app_windows.zip
  macos-build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: brew update
      - run: brew install sdl2
      - run: clang app.c -o app `sdl2-config --cflags --libs`
      - run: zip app_macos.zip app
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
         files: app_macos.zip
  linux-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install zip libsdl2-dev
      - run: gcc app.c -o app `sdl2-config --cflags --libs`
      - run: zip app_linux.zip app
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
         files: app_linux.zip
